import Head from 'next/head'
import Image from 'next/image'
import Featured from '../../components/Featured'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <div>
      <Head>
        <title>Café</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link
          rel="icon"
          type="image/png"
          sizes="32x32"
          href="/favicons/icon.svg"
        />
      </Head>
      <Featured></Featured>
    </div>
  );
}
