const data = [
  {
    id: 2,
    title: 'Americano',
    category: 'Drinks',
    price: 1.99,
    img: 'https://firebasestorage.googleapis.com/v0/b/birthday-react-6eca4.appspot.com/o/Drinks%2Famericano.jpg?alt=media&token=3b31f114-4508-42c0-b38a-0932c15c9ca5',
    desc: 'A shot of espresso topped with hot water.',
  },
  {
    id: 3,
    title: 'Cappucino',
    category: 'Drinks',
    price: 4.99,
    img: 'https://firebasestorage.googleapis.com/v0/b/birthday-react-6eca4.appspot.com/o/Drinks%2Fcappucino.jpg?alt=media&token=e25ca6b7-51d0-46f2-93fb-2b87251bd54e',
    desc: 'Made from mostly milk foam with an espresso shot.',
  },

  {
    id: 5,
    title: 'Latte',
    category: 'Drinks',
    price: 4.99,
    img: 'https://firebasestorage.googleapis.com/v0/b/birthday-react-6eca4.appspot.com/o/Drinks%2Flatte.jpg?alt=media&token=077e7289-a6d8-4d4b-a1f9-2cca20c06439',
    desc: 'A drink made with espresso and milk.',
  },
  {
    id: 6,
    title: 'Matcha Latte',
    category: 'Drinks',
    price: 5.99,
    img: 'https://firebasestorage.googleapis.com/v0/b/birthday-react-6eca4.appspot.com/o/Drinks%2Flatte-matcha.jpg?alt=media&token=6827a307-9f8a-4303-a1c3-041bea33cd22',
    desc: 'Green matcha tea powder and milk to create a caffeinated coffee alternative. ',
  },
  {
    id: 7,
    title: 'Macchiato',
    category: 'Drinks',
    price: 4.99,
    img: 'https://firebasestorage.googleapis.com/v0/b/birthday-react-6eca4.appspot.com/o/Drinks%2Fmacchiato.jpg?alt=media&token=3c891dfa-9af3-428d-af11-971dc9089156',
    desc: 'A steamed milk is creating dense foam and slowly-poured espresso shots.',
  },
  {
    id: 8,
    title: 'Banana Bread',
    category: 'Desserts',
    price: 3.99,
    img: 'https://firebasestorage.googleapis.com/v0/b/birthday-react-6eca4.appspot.com/o/Desserts%2Fbanana-bread.jpg?alt=media&token=e812e6f3-0229-4b64-b08f-9e3f80c93bb7',
    desc: 'Banana bread with chocolate ganache, white sesame froyo, blackberries.',
  },
  {
    id: 9,
    title: 'Brownie',
    category: 'Desserts',
    price: 5.99,
    img: 'https://firebasestorage.googleapis.com/v0/b/birthday-react-6eca4.appspot.com/o/Desserts%2Fbrownie.jpg?alt=media&token=c80ddc90-da59-4390-b5c3-88888903befd',
    desc: 'Fudgy brownie with intense chocolate, raspberries and a vanilla ice-cream.',
  },
  {
    id: 10,
    title: 'Chocolate Chip Cookie',
    category: 'Desserts',
    price: 1.59,
    img: 'https://firebasestorage.googleapis.com/v0/b/birthday-react-6eca4.appspot.com/o/Desserts%2Fcookie.jpg?alt=media&token=60e97773-c08e-4a6e-bf9d-c98ada66bb4a',
    desc: 'Cookie with huge chocolate chunks and full with coconut butter.',
  },
  {
    id: 11,
    title: 'Crepes',
    category: 'Desserts',
    price: 5.99,
    img: 'https://firebasestorage.googleapis.com/v0/b/birthday-react-6eca4.appspot.com/o/Desserts%2Fcrepe.jpg?alt=media&token=1d78927f-1331-4dd0-b74f-6c21716a6693',
    desc: 'French crepes folded with jam and fruits or ham and cheese.',
  },
  {
    id: 12,
    title: 'Macaron',
    category: 'Desserts',
    price: 3.99,
    img: 'https://firebasestorage.googleapis.com/v0/b/birthday-react-6eca4.appspot.com/o/Desserts%2Fmacaron.jpg?alt=media&token=2747ac48-728f-4f91-84c3-a77a84ae13d9',
    desc: 'Meringue cookies are sandwiched together with chocolate,vanilla.',
  },
  {
    id: 13,
    title: 'Mousse',
    category: 'Desserts',
    price: 3.99,
    img: 'https://firebasestorage.googleapis.com/v0/b/birthday-react-6eca4.appspot.com/o/Desserts%2Fmousse.jpg?alt=media&token=355e29df-c1bd-4682-b540-4fa7ac3dd94d',
    desc: 'Sweet creme with a foam, whipped cream and bananas.',
  },
  {
    id: 14,
    title: 'Pie',
    category: 'Desserts',
    price: 5.5,
    img: 'https://firebasestorage.googleapis.com/v0/b/birthday-react-6eca4.appspot.com/o/Desserts%2Fpie.jpg?alt=media&token=508ac837-6089-4c90-b981-a534eb38ecbd',
    desc: 'Crisp apples mixed with cinnamon, nutmeg, and sugar, then placed between handmade flaky crust.',
  },
  {
    id: 15,
    title: 'Fruit Tart',
    category: 'Desserts',
    price: 5.5,
    img: 'https://firebasestorage.googleapis.com/v0/b/birthday-react-6eca4.appspot.com/o/Desserts%2Ftart.jpg?alt=media&token=c182126b-6e12-4330-a113-8b16ca7532c5',
    desc: 'A small pie with vanilla custard, and seasonal fresh fruits.',
  },
  {
    id: 16,
    title: 'Tiramisu',
    category: 'Desserts',
    price: 4.5,
    img: 'https://firebasestorage.googleapis.com/v0/b/birthday-react-6eca4.appspot.com/o/Desserts%2Ftiramisu.jpg?alt=media&token=a551ffac-d2aa-43a1-bec8-ae1fcfb2ec38',
    desc: 'Made with ladyfinger cookies, espresso, mascarpone, Marsala wine, and rum.',
  },
  {
    id: 17,
    title: 'Salmon Salad',
    category: 'Salad',
    price: 14.99,
    img: 'https://firebasestorage.googleapis.com/v0/b/birthday-react-6eca4.appspot.com/o/Salads%2Fsalad-1.jpg?alt=media&token=b15c39fe-cff7-4dd4-8012-6a55beba6470',
    desc: 'Swedish Style sandwich on crisp rye bread with smoked salmon, fresh greens and capers.',
  },
  {
    id: 18,
    title: 'Pomegranate Salad',
    category: 'Salad',
    price: 12.99,
    img: 'https://firebasestorage.googleapis.com/v0/b/birthday-react-6eca4.appspot.com/o/Salads%2Fsalad-2.jpg?alt=media&token=87fbfc9d-f06b-4f23-b74a-3c9d54ac1c92',
    desc: 'Pomegranate, toasted pecans, dried cranberries and blue cheese. Served with olive dill bread. ',
  },
  {
    id: 19,
    title: 'Avocado Salad',
    category: 'Salad',
    price: 10.99,
    img: 'https://firebasestorage.googleapis.com/v0/b/birthday-react-6eca4.appspot.com/o/Salads%2Fsalad-3.jpg?alt=media&token=d69b25c0-3f3a-428a-a789-6dbeb7b90f29',
    desc: 'Laden with dried cranberries, toasted pecans and a hint of classic Scandinavian spices.',
  },
  {
    id: 20,
    title: 'Vegetable Salad',
    category: 'Salad',
    price: 11.99,
    img: 'https://firebasestorage.googleapis.com/v0/b/birthday-react-6eca4.appspot.com/o/Salads%2Fsalad-4.jpg?alt=media&token=d49f8f85-ab17-40cd-9516-b64f0c9a93e1',
    desc: 'Served on bed of lettuce with tomatoes, cucumbers and olive dill flat bread.',
  },
  {
    id: 21,
    title: 'Rice with Salad',
    category: 'Salad',
    price: 14.99,
    img: 'https://firebasestorage.googleapis.com/v0/b/birthday-react-6eca4.appspot.com/o/Salads%2Fsalad-5.jpg?alt=media&token=eb4434c4-c6ad-4783-895f-bcf1644b391b',
    desc: 'Smoked beef and basmati rice with fresh greens and Swedish lingonberries.',
  },
  {
    id: 22,
    title: 'Greens Salad',
    category: 'Salad',
    price: 10.99,
    img: 'https://firebasestorage.googleapis.com/v0/b/birthday-react-6eca4.appspot.com/o/Salads%2Fsalad-kale.jpg?alt=media&token=8ef501da-a48b-435d-b3e6-b3ea19429fe7',
    desc: 'Crisp kale mounded with our secret recipe “schmeer” on artisan bread.',
  },
  {
    id: 23,
    title: 'Pumpkin Salad',
    category: 'Salad',
    price: 15.99,
    img: 'https://firebasestorage.googleapis.com/v0/b/birthday-react-6eca4.appspot.com/o/Salads%2Fsalad-pumpkin.jpg?alt=media&token=84cd22b9-a077-45d4-91cb-57428983213c',
    desc: 'Black forest smoked pumpkin and sharp cheddar layered on sauerkraut rye.',
  },
  {
    id: 24,
    title: 'Basic Brekfast',
    category: 'Brekfast',
    price: 10.99,
    img: 'https://firebasestorage.googleapis.com/v0/b/birthday-react-6eca4.appspot.com/o/Breakfast%2Fbreakfast.jpg?alt=media&token=ab4fa6ce-975e-4183-88b5-59fb95368867',
    desc: 'Serving with toast or warm tortillas for breakfast.',
  },
  {
    id: 25,
    title: 'Egg Benedict',
    category: 'Brekfast',
    price: 12.99,
    img: 'https://firebasestorage.googleapis.com/v0/b/birthday-react-6eca4.appspot.com/o/Breakfast%2Fegg-benedict.jpg?alt=media&token=14f284df-62c6-4a9b-9cfa-0ab2b5f1b685',
    desc: 'The yolk runs into lemony hollandaise and with a English muffin,Canadian bacon.',
  },
  {
    id: 26,
    title: 'Egg Toast',
    category: 'Brekfast',
    price: 11.99,
    img: 'https://firebasestorage.googleapis.com/v0/b/birthday-react-6eca4.appspot.com/o/Breakfast%2Fegg-toast.jpg?alt=media&token=2a837e42-24f1-4780-85e1-c02c200eec6e',
    desc: 'Sandwich oozing with warm pesto and bright yellow egg yolk.',
  },
  {
    id: 27,
    title: 'Smoothie',
    category: 'Brekfast',
    price: 10.99,
    img: 'https://firebasestorage.googleapis.com/v0/b/birthday-react-6eca4.appspot.com/o/Breakfast%2Fsmoothie.jpg?alt=media&token=868b9b83-56ef-4856-93c0-1f8437df1f23',
    desc: 'Breakfast, lunch or dessert, this smoothie bowl is a treat any which way you enjoy it!',
  },
  {
    id: 28,
    title: 'Toasts',
    category: 'Brekfast',
    price: 11.5,
    img: 'https://firebasestorage.googleapis.com/v0/b/birthday-react-6eca4.appspot.com/o/Breakfast%2Ftoasts.jpg?alt=media&token=66314283-7397-44ad-b2d8-e16865015ae7',
    desc: 'Pancakes with caramelized bananas and toasted pecans.',
  },
  {
    id: 29,
    title: 'Chicken Broccoli ',
    category: 'Dinner',
    price: 15.99,
    img: 'https://firebasestorage.googleapis.com/v0/b/birthday-react-6eca4.appspot.com/o/Dinner%2Fbroccoli-meal.jpg?alt=media&token=5fd149e5-5c8a-4809-84ca-d9e2ba2957db',
    desc: 'Simmered in a creamy mushroom, broccoli and Marsala sauce.',
  },
  {
    id: 30,
    title: 'Noodle',
    category: 'Dinner',
    price: 13.99,
    img: 'https://firebasestorage.googleapis.com/v0/b/birthday-react-6eca4.appspot.com/o/Dinner%2Fnoodle.jpg?alt=media&token=90ccf843-fb25-4ae3-bc8f-425e0e3b0441',
    desc: 'Cooked-til-crisp ground pork, and creamy Thai peanut dressing and rice noodles.',
  },
  {
    id: 31,
    title: 'Shrimp Noodle',
    category: 'Dinner',
    price: 15.5,
    img: 'https://firebasestorage.googleapis.com/v0/b/birthday-react-6eca4.appspot.com/o/Dinner%2Fshrimp-noodle.jpg?alt=media&token=32bc7e9a-37a6-47ec-9741-77236bec21d3',
    desc: 'Fresh, udon noodles with shrimps and rich, silky coconut milk.',
  },
  {
    id: 32,
    title: 'Snack Plate',
    category: 'Dinner',
    price: 11.99,
    img: 'https://firebasestorage.googleapis.com/v0/b/birthday-react-6eca4.appspot.com/o/Dinner%2Fsnack-plate.jpg?alt=media&token=4d4bfc93-3cfd-4716-94f3-0ef4c16f54f4',
    desc: 'A a few favorite snacks and a glass of wine.',
  },
  {
    id: 33,
    title: 'Pumpkin Soup',
    category: 'Dinner',
    price: 6.5,
    img: 'https://firebasestorage.googleapis.com/v0/b/birthday-react-6eca4.appspot.com/o/Dinner%2Fsoup.jpg?alt=media&token=5641b3d8-b3de-4871-9975-ebbb7454da6c',
    desc: 'Creamy vegan pumpkin curry soup is beloved in our restaurant.',
  },
  {
    id: 34,
    title: 'Sushi',
    category: 'Dinner',
    price: 12.99,
    img: 'https://firebasestorage.googleapis.com/v0/b/birthday-react-6eca4.appspot.com/o/Dinner%2Fsushi-plate.jpg?alt=media&token=cf4170a8-798f-410f-ab24-a7ae6176ea53',
    desc: 'Seared salmon on a rice along with silky avocado, cucumber and salty nori.',
  },
  {
    id: 35,
    title: 'Tacos',
    category: 'Dinner',
    price: 13.99,
    img: 'https://firebasestorage.googleapis.com/v0/b/birthday-react-6eca4.appspot.com/o/Dinner%2Ftaco.jpg?alt=media&token=266b4f65-52bf-4459-b4f9-d775b7ca79c2',
    desc: 'Bacon, eggs, avocado and cheddar cheese and tacos.',
  },
];

/*
{ id: 1, title: '', category: '', price: 1.99, img: '', desc: '' },
*/

export default data;
