const menu = [
  {
    id: 1,
    title: 'Breakfast Plate',
    category: 'Breakfast',
    price: '9.99€',
    img: 'https://firebasestorage.googleapis.com/v0/b/birthday-react-6eca4.appspot.com/o/FoodHunt%2Fimage%201.png?alt=media&token=2a73ecce-03c0-41f8-b697-e0acf12cfd1d',
    desc: 'A whole breakfast plate',
  },
  {
    id: 2,
    title: 'Pancakes',
    category: 'Breakfast',
    price: '8.99€',
    img: 'https://firebasestorage.googleapis.com/v0/b/birthday-react-6eca4.appspot.com/o/FoodHunt%2Fimage%201.png?alt=media&token=2a73ecce-03c0-41f8-b697-e0acf12cfd1d',
    desc: 'Delicious pancakes with maple syrup.',
  },
  {
    id: 3,
    title: 'Toast with Ham',
    category: 'Breakfast',
    price: '8.99€',
    img: 'https://firebasestorage.googleapis.com/v0/b/birthday-react-6eca4.appspot.com/o/FoodHunt%2Fimage%201.png?alt=media&token=2a73ecce-03c0-41f8-b697-e0acf12cfd1d',
    desc: 'Ham and goat cheese',
  },
  {
    id: 4,
    title: 'Smoothie Bowl',
    category: 'Breakfast',
    price: '10.99€',
    img: 'https://firebasestorage.googleapis.com/v0/b/birthday-react-6eca4.appspot.com/o/FoodHunt%2Fimage%201.png?alt=media&token=2a73ecce-03c0-41f8-b697-e0acf12cfd1d',
    desc: 'With delicious fruit a protein resource.',
  },
  {
    id: 5,
    title: 'Salmon Salad',
    category: 'Lunch',
    price: '13.99€',
    img: 'https://firebasestorage.googleapis.com/v0/b/birthday-react-6eca4.appspot.com/o/FoodHunt%2Fimage%202.png?alt=media&token=9330623b-ae63-4a9d-873f-ff8e4fb125ce',
    desc: 'Grilled salmon with greens.',
  },
  {
    id: 6,
    title: 'Couscous Chicken',
    category: 'Lunch',
    price: '13.99€',
    img: 'https://firebasestorage.googleapis.com/v0/b/birthday-react-6eca4.appspot.com/o/FoodHunt%2Fimage%202.png?alt=media&token=9330623b-ae63-4a9d-873f-ff8e4fb125ce',
    desc: 'Chickens with couscous and sauce.',
  },
  {
    id: 7,
    title: 'Salmon Salad',
    category: 'Lunch',
    price: '13.99€',
    img: 'https://firebasestorage.googleapis.com/v0/b/birthday-react-6eca4.appspot.com/o/FoodHunt%2Fimage%202.png?alt=media&token=9330623b-ae63-4a9d-873f-ff8e4fb125ce',
    desc: 'Grilled salmon with greens.',
  },
  {
    id: 8,
    title: 'Salmon Salad',
    category: 'Lunch',
    price: '13.99€',
    img: 'https://firebasestorage.googleapis.com/v0/b/birthday-react-6eca4.appspot.com/o/FoodHunt%2Fimage%202.png?alt=media&token=9330623b-ae63-4a9d-873f-ff8e4fb125ce',
    desc: 'Grilled salmon with greens.',
  },
  {
    id: 9,
    title: 'Salmon Salad',
    category: 'Lunch',
    price: '13.99€',
    img: 'https://firebasestorage.googleapis.com/v0/b/birthday-react-6eca4.appspot.com/o/FoodHunt%2Fimage%202.png?alt=media&token=9330623b-ae63-4a9d-873f-ff8e4fb125ce',
    desc: 'Grilled salmon with greens.',
  },
  {
    id: 10,
    title: 'Salmon Salad',
    category: 'Dinner',
    price: '13.99€',
    img: 'https://firebasestorage.googleapis.com/v0/b/birthday-react-6eca4.appspot.com/o/FoodHunt%2Fimage%206.png?alt=media&token=007238d0-03ad-4a65-bfcb-e37fb474ead1',
    desc: 'Grilled salmon with greens.',
  },
  {
    id: 11,
    title: 'Salmon Salad',
    category: 'Dinner',
    price: '13.99€',
    img: 'https://firebasestorage.googleapis.com/v0/b/birthday-react-6eca4.appspot.com/o/FoodHunt%2Fimage%206.png?alt=media&token=007238d0-03ad-4a65-bfcb-e37fb474ead1',
    desc: 'Grilled salmon with greens.',
  },
  {
    id: 12,
    title: 'Salmon Salad',
    category: 'Dinner',
    price: '13.99€',
    img: 'https://firebasestorage.googleapis.com/v0/b/birthday-react-6eca4.appspot.com/o/FoodHunt%2Fimage%206.png?alt=media&token=007238d0-03ad-4a65-bfcb-e37fb474ead1',
    desc: 'Grilled salmon with greens.',
  },
];

export default menu;
