const data = [
  {
    id: 1,
    title: 'KNIT CARDIGAN',
    category: 'chic',
    price: 45.99,
    img: 'https://firebasestorage.googleapis.com/v0/b/birthday-react-6eca4.appspot.com/o/Clothing%2Fchic%2F10.jpg?alt=media&token=5012e84b-b96b-4f73-bfbc-f606d7bc011f',
    desc: 'CROPPED CARDIGAN WITH A ROUND NECK AND LONG SLEEVES.',
  },
  {
    id: 2,
    title: 'SKIRT WITH MINI RUFFLES',
    category: 'chic',
    price: 29.99,
    img: 'https://firebasestorage.googleapis.com/v0/b/birthday-react-6eca4.appspot.com/o/Clothing%2Fchic%2F16.jfif?alt=media&token=42fe1cf8-6430-4374-ab40-27dbb50fc0c6',
    desc: 'HIGH-WAIST SHORT SKIRT WITH POCKETS ON THE FRONT.',
  },

  {
    id: 3,
    title: 'FLORAL MINI DRESS',
    category: 'chich',
    price: 35.99,
    img: 'https://firebasestorage.googleapis.com/v0/b/birthday-react-6eca4.appspot.com/o/Clothing%2Fchic%2F17.jfif?alt=media&token=7e997dfb-b97c-4f78-b1f2-22e1ed0e0ad0',
    desc: 'V-NECK DRESS WITH THIN CROSSED STRAPS. ELASTICATED BACK.',
  },
  {
    id: 4,
    title: 'FRANÇOISE TROUSERS',
    category: 'chic',
    price: 29.99,
    img: 'https://firebasestorage.googleapis.com/v0/b/birthday-react-6eca4.appspot.com/o/Clothing%2Fchic%2F18.jfif?alt=media&token=1a657552-b848-4b76-a08d-eaad4765e0de',
    desc: 'HIGH-WAIST TROUSERS WITH A STRAIGHT-LEG DESIGN. ',
  },
  {
    id: 5,
    title: 'DRAPED DRESS',
    category: 'chic',
    price: 49.99,
    img: 'https://firebasestorage.googleapis.com/v0/b/birthday-react-6eca4.appspot.com/o/Clothing%2Fchic%2F1_.jfif?alt=media&token=f3977bb0-6c54-4fea-bd86-b1ce3ece872d',
    desc: 'DRESS WITH SHORT PUFF SLEEVES. DRAPED FABRIC AND CONTRAST LINING.',
  },
  {
    id: 6,
    title: 'MINI DRESS',
    category: 'chic',
    price: 59.99,
    img: 'https://firebasestorage.googleapis.com/v0/b/birthday-react-6eca4.appspot.com/o/Clothing%2Fchic%2F9.jpg?alt=media&token=0cf872af-e9cf-44fb-a790-033c71115e5a',
    desc: 'DRESS WITH A SURPLICE NECKLINE AND THIN STRAPS.',
  },
  {
    id: 7,
    title: 'FLORAL SATIN DRESS',
    category: 'chic',
    price: 34.99,
    img: 'https://firebasestorage.googleapis.com/v0/b/birthday-react-6eca4.appspot.com/o/Clothing%2Fchic%2Fa.jpg?alt=media&token=61018e5d-fe45-4d2d-9828-b94cf0c7a9cb',
    desc: 'DRESS WITH A STRAIGHT-CUT NECKLINE AND THIN STRAPS THAT CROSS AT THE BACK.',
  },
  {
    id: 8,
    title: 'OVERSIZED BLAZER',
    category: 'chic',
    price: 84.99,
    img: 'https://firebasestorage.googleapis.com/v0/b/birthday-react-6eca4.appspot.com/o/Clothing%2Fchic%2F3.jpg?alt=media&token=339f17bf-9e1b-4b31-a12a-c403b8c0fed3',
    desc: 'BLAZER WITH A COLLAR AND LONG SLEEVES FRONT POCKETS AND CHEST POCKET',
  },
  {
    id: 9,
    title: 'STRAIGHT JEANS',
    category: 'casual',
    price: 59.99,
    img: 'https://firebasestorage.googleapis.com/v0/b/birthday-react-6eca4.appspot.com/o/Clothing%2Fcasual%2F13.jpg?alt=media&token=030d137d-49a3-4782-bffa-d1ec2939c69c',
    desc: 'HIGH-RISE JEANS FEATURING REAR PATCH POCKETS ',
  },
  {
    id: 10,
    title: 'OVERSIZED SHIRT',
    category: 'casual',
    price: 39.99,
    img: 'https://firebasestorage.googleapis.com/v0/b/birthday-react-6eca4.appspot.com/o/Clothing%2Fcasual%2F14.jpg?alt=media&token=0ea53e5a-bfc6-438a-8ff1-b112c8544113',
    desc: 'LOOSE-FITTING BUTTON-COLLARED SHIRT WITH CUFFED LONG SLEEVES',
  },
  {
    id: 11,
    title: 'ANKLE BOOTS',
    category: 'casual',
    price: 99.99,
    img: 'https://firebasestorage.googleapis.com/v0/b/birthday-react-6eca4.appspot.com/o/Clothing%2Fcasual%2F15.jpg?alt=media&token=039cfbcb-abb4-4aed-96f8-3203803e8c2d',
    desc: 'FLATFORM ANKLE BOOTS. ELASTIC GORES ON THE SIDES',
  },
  {
    id: 12,
    title: 'MINI CITY BAG',
    category: 'casual',
    price: 49.99,
    img: 'https://firebasestorage.googleapis.com/v0/b/birthday-react-6eca4.appspot.com/o/Clothing%2Fcasual%2F2.jpg?alt=media&token=0d4e91d5-735f-45fa-9e2f-2e0b03fcb25a',
    desc: 'MINI CITY BAG LINED INTERIOR WITH POCKETS',
  },
  {
    id: 13,
    title: 'DOUBLE-BREASTED TRENCH COAT',
    category: 'casual',
    price: 119.99,
    img: 'https://firebasestorage.googleapis.com/v0/b/birthday-react-6eca4.appspot.com/o/Clothing%2Fcasual%2F6.jpg?alt=media&token=95096c60-bf05-4983-8cfc-0bd95d40ba10',
    desc: ' TRENCH COAT WITH A LAPEL COLLAR TAB AND SLEEVESBELOW THE ELBOW',
  },
  {
    id: 14,
    title: 'CARDIGAN WITH BUTTONS',
    category: 'casual',
    price: 29.99,
    img: 'https://firebasestorage.googleapis.com/v0/b/birthday-react-6eca4.appspot.com/o/Clothing%2Fcasual%2F6_.jfif?alt=media&token=5ce7c40f-8dbc-4608-b27c-43b767e4a38f',
    desc: 'CARDIGAN WITH A SLOT COLLAR AND LONG CUFFED SLEEVES',
  },
  {
    id: 15,
    title: 'Faux shearling-lined biker jacket',
    category: 'casual',
    price: 99.99,
    img: 'https://firebasestorage.googleapis.com/v0/b/birthday-react-6eca4.appspot.com/o/Clothing%2Fcasual%2F8.jpg?alt=media&token=4283d619-8012-49f5-ab1c-cfb8f1200cdf',
    desc: 'Faux leather, biker design. Lapel-collar V-neck collar',
  },
  {
    id: 16,
    title: 'Sailor-collar Sweater',
    category: 'sporty',
    price: 39.99,
    img: 'https://firebasestorage.googleapis.com/v0/b/birthday-react-6eca4.appspot.com/o/Clothing%2Fsporty%2F3_.jfif?alt=media&token=976d1546-d7c0-449c-9ba2-abbed882f24e',
    desc: 'Rib-knitted, extra-fine wool with a large zipped sailor collar',
  },
  {
    id: 17,
    title: 'SEAMLESS LEGGINGS',
    category: 'sporty',
    price: 39.99,
    img: 'https://firebasestorage.googleapis.com/v0/b/birthday-react-6eca4.appspot.com/o/Clothing%2Fsporty%2Fd.jpg?alt=media&token=8b94054f-bcda-4e1a-b15d-79615dec147f',
    desc: 'LIMITLESS CONTOUR COLLECTION HIGH-WAIST LEGGINGS',
  },
  {
    id: 18,
    title: 'New Balance 550',
    category: 'sporty',
    price: 129.99,
    img: 'https://firebasestorage.googleapis.com/v0/b/birthday-react-6eca4.appspot.com/o/Clothing%2Fsporty%2F7.jpg?alt=media&token=380b82e0-f3bc-4350-957c-70fab7538fff',
    desc: 'TRAINERS IN A COMBINATION OF MATERIALS',
  },
  {
    id: 19,
    title: 'ROLLER SHORTS',
    category: 'sporty',
    price: 59.99,
    img: 'https://firebasestorage.googleapis.com/v0/b/birthday-react-6eca4.appspot.com/o/Clothing%2Fsporty%2Fb.jpg?alt=media&token=c3750ee6-956b-44b7-83b6-daf52b7a6b0e',
    desc: 'HIGH-WAIST SHORTS FEATURING AN ELASTIC WAISTBAND',
  },
  {
    id: 20,
    title: 'TANK TOP',
    category: 'sporty',
    price: 29.99,
    img: 'https://firebasestorage.googleapis.com/v0/b/birthday-react-6eca4.appspot.com/o/Clothing%2Fsporty%2Fc.jpg?alt=media&token=938a9d6d-81a2-4d8c-afdf-23c571fa47b7',
    desc: 'TOP WITH A ROUND NECK AND WIDE STRAPS',
  },
  {
    id: 21,
    title: 'CHECK SCARF',
    category: 'sporty',
    price: 49.99,
    img: 'https://firebasestorage.googleapis.com/v0/b/birthday-react-6eca4.appspot.com/o/Clothing%2Fsporty%2Fe.jpg?alt=media&token=7a63df5e-9220-4a91-a329-e83bf7f4e9d3',
    desc: 'SOFT-TOUCH SCARF WITH FRAYED EDGES',
  },
  {
    id: 22,
    title: 'MASCULINE TROUSERS',
    category: 'sporty',
    price: 79.99,
    img: 'https://firebasestorage.googleapis.com/v0/b/birthday-react-6eca4.appspot.com/o/Clothing%2Fsporty%2Ff.jpg?alt=media&token=5bb4bf83-6653-431c-b7f5-f8433fbbbba3',
    desc: 'HIGH-WAIST TROUSERS WITH FRONT POCKETS AND REAR WELT POCKETS',
  },
  {
    id: 23,
    title: 'BASIC SWEATSHIRT',
    category: 'sporty',
    price: 29.99,
    img: 'https://firebasestorage.googleapis.com/v0/b/birthday-react-6eca4.appspot.com/o/Clothing%2Fsporty%2Fg.jpg?alt=media&token=011ff120-ecda-4e99-b753-eb0d2c6c0921',
    desc: 'LONG SLEEVE SWEATSHIRT WITH A ROUND NECKLINE AND RIBBED TRIMS',
  },
];

/*
{ id: 1, title: '', category: 'sporty', price: 1.99, img: '', desc: '' },
*/

export default data;
